/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeuideneme;

/**
 *
 * @author user
 */
public class DoctorListingPage extends javax.swing.JFrame {

    /**
     * Creates new form DoctorListingPage
     * @param rowID
     */
    public DoctorListingPage(int rowID) {
        //initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        uyeLabelDontChange = new javax.swing.JButton();
        uyeBt = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        PhotoIconLabelDoctorPic = new javax.swing.JLabel();
        DocNameLabel = new javax.swing.JLabel();
        BranchDoctorLabel = new javax.swing.JLabel();
        CityLabelDoc = new javax.swing.JLabel();
        ProvinceDocLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        tarihComboBox = new javax.swing.JComboBox<>();
        SaatKomboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        RandevuAlBt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1440, 1024));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_component_assets/LOGO 2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, 100));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 310, 31));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_component_assets/icon_magnifying_glass.png"))); // NOI18N
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 30, 30));

        uyeLabelDontChange.setBackground(new java.awt.Color(255, 0, 0));
        uyeLabelDontChange.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        uyeLabelDontChange.setForeground(new java.awt.Color(255, 255, 255));
        uyeLabelDontChange.setText("UYE");
        uyeLabelDontChange.setBorderPainted(false);
        uyeLabelDontChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uyeLabelDontChangeActionPerformed(evt);
            }
        });
        jPanel1.add(uyeLabelDontChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 30, 70, 30));

        uyeBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_component_assets/User_Button.png"))); // NOI18N
        jPanel1.add(uyeBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 20, 140, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1470, 110));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(PhotoIconLabelDoctorPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 60, 164, 191));

        DocNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel2.add(DocNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 60, 987, 67));

        BranchDoctorLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(BranchDoctorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 139, 255, 43));

        CityLabelDoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(CityLabelDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 188, 228, 43));

        ProvinceDocLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(ProvinceDocLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 188, 232, 43));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 740, 360));

        tarihComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        tarihComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarihComboBoxActionPerformed(evt);
            }
        });
        jPanel2.add(tarihComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 340, 200, 50));

        SaatKomboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(SaatKomboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 340, 190, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Tarih");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 290, 190, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Saat");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 290, 170, 40));

        RandevuAlBt.setBackground(new java.awt.Color(255, 0, 0));
        RandevuAlBt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RandevuAlBt.setForeground(new java.awt.Color(255, 255, 255));
        RandevuAlBt.setText("Randevu Al");
        jPanel2.add(RandevuAlBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 430, 170, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1470, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void uyeLabelDontChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uyeLabelDontChangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uyeLabelDontChangeActionPerformed

    private void tarihComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarihComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tarihComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorListingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorListingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorListingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorListingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorListingPage().setVisible(true);
            }
        });
        */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BranchDoctorLabel;
    private javax.swing.JLabel CityLabelDoc;
    private javax.swing.JLabel DocNameLabel;
    private javax.swing.JLabel PhotoIconLabelDoctorPic;
    private javax.swing.JLabel ProvinceDocLabel;
    private javax.swing.JButton RandevuAlBt;
    private javax.swing.JComboBox<String> SaatKomboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> tarihComboBox;
    private javax.swing.JLabel uyeBt;
    private javax.swing.JButton uyeLabelDontChange;
    // End of variables declaration//GEN-END:variables
}
