/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.projeuideneme;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author feritbilgi
 */
public class Listing extends javax.swing.JPanel {
        String email = "";

    /**
     * Creates new form Listing
     */
    public Listing(String emailString) {
        initComponents();
        Connection con = doctorDbConnection.connect();
        PreparedStatement ps = null;
        ResultSet rs = null;
        
        try{
            String sql = "Select * from doctors where email = ?";
            ps = con.prepareStatement(sql);
            ps.setString(1, emailString);
            rs = ps.executeQuery();
            this.email = emailString;
            
            //we are reading one row, so no need to loop
            String firstName = rs.getString(1);
            String statueOfDoctor = rs.getString("statue");
            String name = statueOfDoctor + " Dr " + firstName;
            
            String branchOfDoctor = rs.getString("branch");
            doctorNameText.setText(name);
            bracnhText.setText(branchOfDoctor);
            locationText.setText("Ankara");
            jTextArea1.setText(rs.getString("about"));
        }catch(SQLException e){
            System.out.println(e.toString());
        }finally{
            try{
                rs.close();
                ps.close();
                con.close();
            }catch(SQLException e){
                System.out.println(e.toString());
            }
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        locationText = new javax.swing.JLabel();
        bracnhText = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        DoctorImage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        doctorNameText = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        locationText.setBackground(new java.awt.Color(255, 255, 255));
        locationText.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 36)); // NOI18N
        locationText.setForeground(new java.awt.Color(0, 0, 0));
        locationText.setText("Location Text");
        add(locationText, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 270, 110));

        bracnhText.setBackground(new java.awt.Color(255, 255, 255));
        bracnhText.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 36)); // NOI18N
        bracnhText.setForeground(new java.awt.Color(0, 0, 0));
        bracnhText.setText("Branch Text");
        add(bracnhText, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 270, 110));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 660, 210));

        DoctorImage.setBackground(new java.awt.Color(255, 255, 255));
        DoctorImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_component_assets/DoctorImage.png"))); // NOI18N
        DoctorImage.setText("jLabel1");
        add(DoctorImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, -3, 300, 310));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_component_assets/hosLocationIcon.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 40, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_component_assets/Arrow.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 40, 40));

        doctorNameText.setBackground(new java.awt.Color(255, 255, 255));
        doctorNameText.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        doctorNameText.setForeground(new java.awt.Color(0, 0, 0));
        doctorNameText.setText("Doctor Something");
        add(doctorNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 280, 80));
    }// </editor-fold>//GEN-END:initComponents

    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DoctorImage;
    private javax.swing.JLabel bracnhText;
    private javax.swing.JButton doctorNameText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel locationText;
    // End of variables declaration//GEN-END:variables
}
