/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeuideneme;

/**
 *
 * @author aslikanber
 */
public class searchFrame extends javax.swing.JFrame {

    /**
     * Creates new form searchFrame
     */
    public searchFrame() {
 
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchPanel = new javax.swing.JPanel();
        searchBar = new javax.swing.JTextField();
        patientAccountButton = new javax.swing.JButton();
        insuranceButton = new javax.swing.JButton();
        appointmentsButton = new javax.swing.JButton();
        logoLabel = new javax.swing.JLabel();
        listFilterPanel = new javax.swing.JPanel();
        listingPanel = new javax.swing.JPanel();
        listingBox = new javax.swing.JComboBox<>();
        filterPanel = new javax.swing.JPanel();
        ezcaneFilter = new javax.swing.JCheckBox();
        sigortaFilter = new javax.swing.JCheckBox();
        resultPanel = new javax.swing.JScrollPane();
        adjustableResultPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchPanel.setBackground(new java.awt.Color(255, 255, 255));
        searchPanel.setPreferredSize(new java.awt.Dimension(1440, 128));

        searchBar.setText("jTextField1");
        searchBar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.gray));
        searchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBarActionPerformed(evt);
            }
        });

        patientAccountButton.setFont(new java.awt.Font("K2D", 1, 24)); // NOI18N
        patientAccountButton.setForeground(java.awt.Color.red);
        patientAccountButton.setText("Randevularım");
        patientAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientAccountButtonActionPerformed(evt);
            }
        });

        insuranceButton.setFont(new java.awt.Font("K2D", 1, 24)); // NOI18N
        insuranceButton.setForeground(java.awt.Color.red);
        insuranceButton.setText("Sigortalarım");
        insuranceButton.setToolTipText("");
        insuranceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insuranceButtonActionPerformed(evt);
            }
        });

        appointmentsButton.setIcon(new javax.swing.ImageIcon("/Users/aslikanber/Desktop/User_Button.png")); // NOI18N
        appointmentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appointmentsButtonActionPerformed(evt);
            }
        });

        logoLabel.setIcon(new javax.swing.ImageIcon("/Users/aslikanber/Desktop/MainMenu (1).png")); // NOI18N
        logoLabel.setText("jLabel2");

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(patientAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(insuranceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111)
                .addComponent(appointmentsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 89, Short.MAX_VALUE))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(appointmentsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(patientAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(insuranceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );

        getContentPane().add(searchPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1478, 134));

        listFilterPanel.setBackground(new java.awt.Color(255, 255, 255));
        listFilterPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        listFilterPanel.setPreferredSize(new java.awt.Dimension(1440, 72));

        listingPanel.setBackground(new java.awt.Color(255, 255, 255));
        listingPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Sıralama", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("K2D", 1, 14))); // NOI18N

        listingBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Önerilen", "En Yakın" }));

        javax.swing.GroupLayout listingPanelLayout = new javax.swing.GroupLayout(listingPanel);
        listingPanel.setLayout(listingPanelLayout);
        listingPanelLayout.setHorizontalGroup(
            listingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listingBox, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        listingPanelLayout.setVerticalGroup(
            listingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listingBox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        filterPanel.setBackground(new java.awt.Color(255, 255, 255));
        filterPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Filtreleme", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("K2D", 1, 14))); // NOI18N

        ezcaneFilter.setFont(new java.awt.Font("K2D", 0, 14)); // NOI18N
        ezcaneFilter.setText("Ezcaneye Yakın");

        sigortaFilter.setFont(new java.awt.Font("K2D", 0, 14)); // NOI18N
        sigortaFilter.setText("Sigortamla Uyumlu");

        javax.swing.GroupLayout filterPanelLayout = new javax.swing.GroupLayout(filterPanel);
        filterPanel.setLayout(filterPanelLayout);
        filterPanelLayout.setHorizontalGroup(
            filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filterPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(ezcaneFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sigortaFilter, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addContainerGap())
        );
        filterPanelLayout.setVerticalGroup(
            filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, filterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ezcaneFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sigortaFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout listFilterPanelLayout = new javax.swing.GroupLayout(listFilterPanel);
        listFilterPanel.setLayout(listFilterPanelLayout);
        listFilterPanelLayout.setHorizontalGroup(
            listFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listFilterPanelLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(listingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(filterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(794, Short.MAX_VALUE))
        );
        listFilterPanelLayout.setVerticalGroup(
            listFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listFilterPanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(listFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(filterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        getContentPane().add(listFilterPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 134, 1478, 80));

        resultPanel.setBackground(new java.awt.Color(255, 255, 255));
        resultPanel.setToolTipText("");
        resultPanel.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        resultPanel.setPreferredSize(new java.awt.Dimension(1440, 824));

        adjustableResultPanel.setBackground(new java.awt.Color(255, 255, 255));
        adjustableResultPanel.setPreferredSize(new java.awt.Dimension(1466, 1000));

        javax.swing.GroupLayout adjustableResultPanelLayout = new javax.swing.GroupLayout(adjustableResultPanel);
        adjustableResultPanel.setLayout(adjustableResultPanelLayout);
        adjustableResultPanelLayout.setHorizontalGroup(
            adjustableResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1468, Short.MAX_VALUE)
        );
        adjustableResultPanelLayout.setVerticalGroup(
            adjustableResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );

        resultPanel.setViewportView(adjustableResultPanel);

        getContentPane().add(resultPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 212, 1480, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBarActionPerformed

    private void insuranceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insuranceButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insuranceButtonActionPerformed

    private void patientAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientAccountButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientAccountButtonActionPerformed

    private void appointmentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appointmentsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_appointmentsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adjustableResultPanel;
    private javax.swing.JButton appointmentsButton;
    private javax.swing.JCheckBox ezcaneFilter;
    private javax.swing.JPanel filterPanel;
    private javax.swing.JButton insuranceButton;
    private javax.swing.JPanel listFilterPanel;
    private javax.swing.JComboBox<String> listingBox;
    private javax.swing.JPanel listingPanel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JButton patientAccountButton;
    private javax.swing.JScrollPane resultPanel;
    private javax.swing.JTextField searchBar;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JCheckBox sigortaFilter;
    // End of variables declaration//GEN-END:variables
}
