/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeuideneme;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;

/**
 *
 * @author feritbilgi
 */
public class SignUpClinicPage extends javax.swing.JFrame {

    /**
     * Creates new form SignUpClinicPage
     */
    
    public SignUpClinicPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        province_textfield = new javax.swing.JTextField();
        name_textfield = new javax.swing.JTextField();
        email_textfield = new javax.swing.JTextField();
        password_field1 = new javax.swing.JPasswordField();
        password_field = new javax.swing.JPasswordField();
        about_textfield = new javax.swing.JTextField();
        branch_textfield = new javax.swing.JTextField();
        signUp_button = new javax.swing.JButton();
        upload_photo = new javax.swing.JButton();
        search_textfield = new javax.swing.JTextField();
        search_button = new javax.swing.JButton();
        login_section_button = new javax.swing.JButton();
        signUp_section_button = new javax.swing.JButton();
        doctors_textfield = new javax.swing.JTextField();
        city_textfield = new javax.swing.JTextField();
        communication_textfield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        province_textfield.setBackground(new java.awt.Color(255, 255, 255));
        province_textfield.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(province_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 400, 540, 60));

        name_textfield.setBackground(new java.awt.Color(255, 255, 255));
        name_textfield.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(name_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 540, 70));

        email_textfield.setBackground(new java.awt.Color(255, 255, 255));
        email_textfield.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(email_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 490, 540, 70));

        password_field1.setBackground(new java.awt.Color(255, 255, 255));
        password_field1.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(password_field1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 590, 540, 70));

        password_field.setBackground(new java.awt.Color(255, 255, 255));
        password_field.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(password_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 680, 540, 70));

        about_textfield.setBackground(new java.awt.Color(255, 255, 255));
        about_textfield.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(about_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 500, 550, 260));

        branch_textfield.setBackground(new java.awt.Color(255, 255, 255));
        branch_textfield.setForeground(new java.awt.Color(0, 0, 0));
        branch_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                branch_textfieldActionPerformed(evt);
            }
        });
        getContentPane().add(branch_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 200, 540, 60));

        signUp_button.setBackground(new java.awt.Color(255, 255, 255));
        signUp_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_component_assets/SignUp_Button.png"))); // NOI18N
        signUp_button.setBorderPainted(false);
        signUp_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUp_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(signUp_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 800, 290, 70));

        upload_photo.setBackground(new java.awt.Color(255, 255, 255));
        upload_photo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_component_assets/UploadPhotoButton.png"))); // NOI18N
        upload_photo.setBorderPainted(false);
        upload_photo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upload_photoActionPerformed(evt);
            }
        });
        getContentPane().add(upload_photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 800, 290, 70));

        search_textfield.setBackground(new java.awt.Color(255, 255, 255));
        search_textfield.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(search_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 540, 70));

        search_button.setBackground(new java.awt.Color(255, 255, 255));
        search_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_component_assets/SearchIcon.png"))); // NOI18N
        search_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(search_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, -1, -1));

        login_section_button.setBackground(new java.awt.Color(255, 255, 255));
        login_section_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_component_assets/LogIn_Button.png"))); // NOI18N
        login_section_button.setBorderPainted(false);
        login_section_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_section_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(login_section_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 40, 230, 50));

        signUp_section_button.setBackground(new java.awt.Color(255, 255, 255));
        signUp_section_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_component_assets/SignUp_Button.png"))); // NOI18N
        signUp_section_button.setBorderPainted(false);
        signUp_section_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUp_section_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(signUp_section_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 40, 210, 50));

        doctors_textfield.setBackground(new java.awt.Color(255, 255, 255));
        doctors_textfield.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(doctors_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 300, 540, 60));

        city_textfield.setBackground(new java.awt.Color(255, 255, 255));
        city_textfield.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(city_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 540, 70));

        communication_textfield.setBackground(new java.awt.Color(255, 255, 255));
        communication_textfield.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(communication_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 540, 70));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Şehir");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 263, 90, 30));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("İlçe");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 370, 110, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_component_assets/SignUp_Menu_Clinic.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_buttonActionPerformed

    private void branch_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branch_textfieldActionPerformed
        
    }//GEN-LAST:event_branch_textfieldActionPerformed

    private void upload_photoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upload_photoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upload_photoActionPerformed

    private void signUp_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUp_buttonActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String firstName = name_textfield.getText();
        String city = city_textfield.getText();
        String email = email_textfield.getText();
        String password = "";
        if (password_field.getText().equals(password_field1.getText())){
            char[] pf = password_field.getPassword();
            password = new String(pf);
        }
        String branches = branch_textfield.getText();
        String province = province_textfield.getText();
        String doctors = doctors_textfield.getText();
        String about = about_textfield.getText();
        
        int phoneNumber = Integer.parseInt(communication_textfield.getText());
        insert(firstName, city, province,  phoneNumber, email, password, branches, about);
        
        
        //Main menu constructor yapılacak(üyelik işlemleri için)
        JFrame menu = new MainMenuClinic(email);
        menu.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_signUp_buttonActionPerformed

    private void signUp_section_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUp_section_buttonActionPerformed
        // TODO add your handling code here:
        JFrame accChose = new AccountChooseJFrame();
        accChose.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_signUp_section_buttonActionPerformed

    private void login_section_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_section_buttonActionPerformed
        // TODO add your handling code here:
        JFrame accChose = new UIDeneme();
        accChose.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_login_section_buttonActionPerformed

    private static void insert(String name, String city, String province, int phoneNumber, String email, String password, String branch,String about){
        Connection con = asliDbConnection.connect();
        PreparedStatement ps = null;
        try{
            String sql = "INSERT INTO clinics(name, city, province, phoneNo, email, password, branch, about) VALUES(?,?,?,?,?,?,?,?)";
            ps = con.prepareStatement(sql);
            ps.setString(1, name);
            ps.setString(2, city);
            ps.setString(3, province);
            ps.setInt(4, phoneNumber);           
            ps.setString(5, email);
            ps.setString(6, password);
            ps.setString(7, branch);
            ps.setString(8, about);            
                        
            
            ps.execute();
            System.out.println("Data has been inserted!");
            
        } catch(SQLException e){
            System.out.println(e.toString());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpClinicPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpClinicPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpClinicPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpClinicPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpClinicPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField about_textfield;
    private javax.swing.JTextField branch_textfield;
    private javax.swing.JTextField city_textfield;
    private javax.swing.JTextField communication_textfield;
    private javax.swing.JTextField doctors_textfield;
    private javax.swing.JTextField email_textfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton login_section_button;
    private javax.swing.JTextField name_textfield;
    private javax.swing.JPasswordField password_field;
    private javax.swing.JPasswordField password_field1;
    private javax.swing.JTextField province_textfield;
    private javax.swing.JButton search_button;
    private javax.swing.JTextField search_textfield;
    private javax.swing.JButton signUp_button;
    private javax.swing.JButton signUp_section_button;
    private javax.swing.JButton upload_photo;
    // End of variables declaration//GEN-END:variables
}
