/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeuideneme;

import javax.swing.JFrame;

/**
 *
 * @author feritbilgi
 */
public class SignUpSectionPage extends javax.swing.JFrame {

    /**
     * Creates new form AcoountChoosement
     */
    public SignUpSectionPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login_section_button = new javax.swing.JButton();
        signUp_section_button = new javax.swing.JButton();
        search_textfield = new javax.swing.JTextField();
        search_button = new javax.swing.JButton();
        clinicSignUp = new javax.swing.JButton();
        patientSignUp = new javax.swing.JButton();
        doktorSignUp = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login_section_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_component_assets/LogIn_Button.png"))); // NOI18N
        login_section_button.setBorderPainted(false);
        login_section_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_section_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(login_section_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 40, 230, 50));

        signUp_section_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_component_assets/SignUp_Button.png"))); // NOI18N
        signUp_section_button.setBorderPainted(false);
        getContentPane().add(signUp_section_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 40, 210, 50));

        search_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_textfieldActionPerformed(evt);
            }
        });
        getContentPane().add(search_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 540, 70));

        search_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_component_assets/SearchIcon.png"))); // NOI18N
        search_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(search_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, -1, -1));

        clinicSignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_component_assets/ClinicSignUp.png"))); // NOI18N
        clinicSignUp.setBorderPainted(false);
        clinicSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clinicSignUpActionPerformed(evt);
            }
        });
        getContentPane().add(clinicSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 540, 290, 70));

        patientSignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_component_assets/PatientSignUp.png"))); // NOI18N
        patientSignUp.setBorderPainted(false);
        patientSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientSignUpActionPerformed(evt);
            }
        });
        getContentPane().add(patientSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 540, 290, 70));

        doktorSignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_component_assets/DoktorSignUp.png"))); // NOI18N
        doktorSignUp.setBorderPainted(false);
        doktorSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doktorSignUpActionPerformed(evt);
            }
        });
        getContentPane().add(doktorSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 540, 290, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_component_assets/LogIn_Menu.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 1030));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_buttonActionPerformed

    private void doktorSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doktorSignUpActionPerformed
        SignUpDoctorPage doctorSignUp = new SignUpDoctorPage();
        doctorSignUp.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_doktorSignUpActionPerformed

    private void clinicSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clinicSignUpActionPerformed
        SignUpClinicPage clinicSignUpPage = new SignUpClinicPage();
        clinicSignUpPage.setVisible(true);
        setVisible(false);     
    }//GEN-LAST:event_clinicSignUpActionPerformed

    private void patientSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientSignUpActionPerformed
        SignUpPatient patientSignUp = new SignUpPatient();
        patientSignUp.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_patientSignUpActionPerformed

    private void search_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_textfieldActionPerformed

    private void login_section_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_section_buttonActionPerformed
        JFrame accChose = new UIDeneme();
        accChose.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_login_section_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpSectionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpSectionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpSectionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpSectionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpSectionPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clinicSignUp;
    private javax.swing.JButton doktorSignUp;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton login_section_button;
    private javax.swing.JButton patientSignUp;
    private javax.swing.JButton search_button;
    private javax.swing.JTextField search_textfield;
    private javax.swing.JButton signUp_section_button;
    // End of variables declaration//GEN-END:variables
}
