/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeuideneme;

import java.awt.Image;

/**
 *
 * @author feritbilgi
 */
public class UIDeneme extends javax.swing.JFrame {

    /**
     * Creates new form UIDeneme
     */
    public UIDeneme() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    javax.swing.ImageIcon logIn_buttonIcon = new javax.swing.ImageIcon();
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        email_textField = new javax.swing.JTextField();
        logIn_section_button = new javax.swing.JButton();
        logIn_button = new javax.swing.JButton();
        signUp_section_button = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        search_button = new javax.swing.JButton();
        search_bar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        email_textField.setBackground(new java.awt.Color(255, 255, 255));
        email_textField.setForeground(new java.awt.Color(0, 0, 0));
        email_textField.setSelectionColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(email_textField, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 533, 480, 60));

        logIn_section_button.setBackground(new java.awt.Color(255, 255, 255));
        logIn_section_button.setForeground(new java.awt.Color(255, 255, 255));
        logIn_section_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_component_assets/LogIn_Button.png"))); // NOI18N
        logIn_section_button.setText("jButton2");
        logIn_section_button.setBorderPainted(false);
        getContentPane().add(logIn_section_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 40, 220, 50));

        logIn_button.setBackground(new java.awt.Color(255, 255, 255));
        logIn_button.setIcon(new javax.swing.ImageIcon("/Users/feritbilgi/Desktop/Engineering/OneDrive/EngineeringCloud/CS102.2/Proje ile Alakalı Dosyalar/ProjeUI/src/main/java/Assets/LogIn.png")); // NOI18N
        logIn_button.setBorder(null);
        logIn_button.setBorderPainted(false);
        logIn_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logIn_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(logIn_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 780, 290, 60));

        signUp_section_button.setBackground(new java.awt.Color(255, 255, 255));
        signUp_section_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_component_assets/SignUp_Button.png"))); // NOI18N
        signUp_section_button.setBorderPainted(false);
        getContentPane().add(signUp_section_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 40, -1, -1));

        passwordField.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 670, 480, 60));

        search_button.setBackground(new java.awt.Color(255, 255, 255));
        search_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_component_assets/SearchIcon.png"))); // NOI18N
        search_button.setBorderPainted(false);
        getContentPane().add(search_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, -1, -1));

        search_bar.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(search_bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 43, 490, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_component_assets/LogIn_Menu.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logIn_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logIn_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logIn_buttonActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIDeneme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIDeneme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIDeneme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIDeneme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIDeneme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email_textField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logIn_button;
    private javax.swing.JButton logIn_section_button;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField search_bar;
    private javax.swing.JButton search_button;
    private javax.swing.JButton signUp_section_button;
    // End of variables declaration//GEN-END:variables
}
