/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeuideneme;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author feritbilgi
 */
public class UIDeneme extends javax.swing.JFrame {

    /**
     * Creates new form UIDeneme
     */
    public UIDeneme() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    javax.swing.ImageIcon logIn_buttonIcon = new javax.swing.ImageIcon();
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        signUp_section_button = new javax.swing.JButton();
        logIn_section_button = new javax.swing.JButton();
        emailLabel = new javax.swing.JLabel();
        email_textField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_component_assets/LOGO_1.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, 250, 260));

        signUp_section_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_component_assets/SignUp_Button.png"))); // NOI18N
        signUp_section_button.setBorderPainted(false);
        signUp_section_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUp_section_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(signUp_section_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 690, -1, -1));

        logIn_section_button.setForeground(new java.awt.Color(255, 255, 255));
        logIn_section_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_component_assets/LogIn_Button.png"))); // NOI18N
        logIn_section_button.setText("jButton2");
        logIn_section_button.setBorderPainted(false);
        logIn_section_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logIn_section_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(logIn_section_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 690, 220, 50));

        emailLabel.setBackground(new java.awt.Color(204, 204, 204));
        emailLabel.setFont(new java.awt.Font("K2D", 1, 24)); // NOI18N
        emailLabel.setForeground(java.awt.Color.red);
        emailLabel.setText("Email");
        jPanel1.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 140, 60));

        email_textField.setSelectionColor(new java.awt.Color(255, 255, 255));
        email_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_textFieldActionPerformed(evt);
            }
        });
        jPanel1.add(email_textField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 480, 60));

        passwordLabel.setFont(new java.awt.Font("K2D", 1, 24)); // NOI18N
        passwordLabel.setForeground(java.awt.Color.red);
        passwordLabel.setText("Password");
        jPanel1.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 530, 170, 40));

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        jPanel1.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 570, 480, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1450, 1030));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signUp_section_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUp_section_buttonActionPerformed
        // TODO add your handling code here:
        JFrame accChose = new AccountChooseJFrame();
        accChose.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_signUp_section_buttonActionPerformed

    private void email_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_textFieldActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void logIn_section_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logIn_section_buttonActionPerformed
        String emailString = email_textField.getText().toString();
    
    
        Connection con = patientDbConnection.connect();
        PreparedStatement ps = null;
        ResultSet rs = null;
        
        boolean equal = false;
        
        try{
            String sql = "Select * from patients where email = ?";
            ps = con.prepareStatement(sql);
            ps.setString(1, emailString);
            
            rs = ps.executeQuery();
            
            //we are reading one row, so no need to loop
            // String firstName = rs.getString(1);
            // String statueOfDoctor = rs.getString("statue");
            // String name = statueOfDoctor + " Dr " + firstName;
            char[] passwordArray = passwordField.getPassword();
            String password = "";
            for (char c : passwordArray){
                password += c;
            }
            String actualPassword = rs.getString("password");
            if (password.equals(actualPassword)){
                equal = true;
            }
            
            // String branchOfDoctor = rs.getString("branch");
            // doctorNameText.setText(name);
            // bracnhText.setText(branchOfDoctor);
            // locationText.setText("Ankara");
            // jTextArea1.setText(rs.getString("about"));
        }catch(SQLException e){
            System.out.println(e.toString());
        }finally{
            try{
                rs.close();
                ps.close();
                con.close();
            }catch(SQLException e){
                System.out.println(e.toString());
            }
            
        }
        
        if (equal == true){
           JFrame frame = new MainMenuPatient(email_textField.getText().toString());
           frame.setVisible(true);
           setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(null, "Yanlış şifre girdiniz.");
        }
    }//GEN-LAST:event_logIn_section_buttonActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIDeneme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIDeneme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIDeneme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIDeneme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIDeneme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField email_textField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logIn_section_button;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton signUp_section_button;
    // End of variables declaration//GEN-END:variables
}
